### ISSUE TITLE
Clorox rebranded as Turbocolor! 

### ISSUE THREAD

**Issue by jorgebucaran** [jorgebucaran/turbocolor#17]
Clorox is now **Turbocolor**! SemVer starts at 1.0.0! 🎉

**Comment by NetOperatorWibby** [comment]
Why does the name of this package keep changing?

**Comment by jorgebucaran** [comment]
@NetOperatorWibby I'm sorry?  The latest change represents a huge shift in the direction of the project, one that will not change. I wrote about it in the [release notes](https://github.com/jorgebucaran/colorette/releases/tag/1.0.0), if you have a moment, please read them.

---
