### ISSUE TITLE
Style stack isn't remembered on multiple uses

### ISSUE THREAD

**Issue by Ovyerus** [jorgebucaran/turbocolor#21]
If you store a style stack in a variable, e.g. `const colour = tc.red.bgCyan.bold`, the first call will be styled as expected, but any further calls to it will only have the first base style. I dunno if this is by design or whatever, but thought I'd report it just in case.

### Reproduction
```js
const tc = require('turbocolor');

const func = tc.red.bgCyan.bold;
const first = func('foobar');
const second  = func('foobar');

console.log(first, second);
```

### Result
![result img](https://erisaaa.is-a-good-waifu.com/f1ced5.png)

**Comment by jorgebucaran** [comment]
@Ovyerus Yup, this behavior is expected. Calling `func` will reset the stack, so the second call fails. 

I would do this:

```js
const func = s => tc.red.bgCyan.bold(s)
const first = func('foobar')
const second  = func('foobar')

console.log(first, second)
```

or this:

```js
const first = tc.red.bgCyan.bold('foobar')
const second  = tc.red.bgCyan.bold('foobar')

console.log(first, second)
```

This behavior was introduced in https://github.com/jorgebucaran/turbocolor/commit/9b1b3c20b94b312109258f54b3d57da3323324d4.

**Comment by Ovyerus** [comment]
Ah I see. Yeah I ended up using the first style with the wrapping clojure, but I wasn't sure if it was intended behaviour or not.

Thanks for the fast reply!

**Comment by jorgebucaran** [comment]
@Ovyerus Just to be clear, you don't need to do:

```js
const func = s => tc.red(s)
```

...since `red` (as well as every other style/color) is a named export. Every style keeps an internal stack/array which is reset to its original value every time you use it as a function.

```js
const  { red } = require("turbocolor")

console.log(red("foo"), red("bar")) // Okay!
```

Now, if you want to create a chain like that, in your original post, your two options are:

```js
const redBgCyanBold = s => tc.red.bgCyan.bold(s)
console.log(redBgCyanBold("foo"), redBgCyanBold("bar"))

// or

console.log(tc.red.bgCyan.bold("foo"), tc.red.bgCyan.bold("bar")) 
```
